version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
  app:
    build: ./app
    command: bash -c "python3 manage.py makemigrations && python3 manage.py migrate && python3 manage.py loaddata all.yaml && python3 manage.py runserver 0.0.0.0:8000"
    ports: 
      - 8000:8000
    depends_on:
      - db