# Generated by Django 4.0.4 on 2022-05-06 04:20

from django.core.management import call_command
from django.db import migrations


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'ticket_manager/fixture/Status.json', app_label='ticket_manager')
    call_command('loaddata', 'ticket_manager/fixture/Category.json', app_label='ticket_manager')


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
