# Generated by Django 4.0.4 on 2022-05-02 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0002_alter_ticket_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(max_length=50)),
                ('order', models.FloatField(verbose_name='上流からの番号')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket_manager.status', verbose_name='ステータス'),
        ),
    ]
