# Generated by Django 4.0.4 on 2022-05-06 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_manager', '0003_status_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ticket_manager.category', verbose_name='カテゴリ'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='deadlinedate',
            field=models.DateTimeField(null=True, verbose_name='終了予定日'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='lastupdatedate',
            field=models.DateTimeField(auto_now=True, verbose_name='最終更新日'),
        ),
    ]
