name: sunday_project CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.10.1]   
    environment:
      name: Github CI

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test
    - name: Measure Test Converage
      id: coverage
      run: |
        coverage run manage.py test ticket_manager && coverage report
    - name: Send Notification
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        SLACK_COLOR: '#5cb85c'
        SLACK_TITLE: 'Passed CI on GitHub Actions :rocket:'
        SLACK_MESSAGE: ${{ join(steps.coverage.outputs.*, '\n') }}
        
